<a href="https://colab.research.google.com/github/kayokfds/trabalhoooo/blob/main/01_Leitura_e_Filtro_B3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dados estão no Google Drive, em FGV > TCC > Dados

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount("/content/drive")
import os

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
caminho_dados = "/content/drive/MyDrive/FGV/TCC/Dados/Brutos"
caminho_output = "/content/drive/MyDrive/FGV/TCC/Dados"

##Leitura de Dados

In [ ]:
nomes_arquivos = [
    'COTAHIST_A2025.TXT',
    'COTAHIST_A2024.TXT',
    'COTAHIST_A2023.TXT',
    'COTAHIST_A2022.TXT',
    'COTAHIST_A2021.TXT',
    'COTAHIST_A2020.TXT',
    'COTAHIST_A2019.TXT',
    'COTAHIST_A2018.TXT',
    'COTAHIST_A2017.TXT',
    'COTAHIST_A2016.TXT'
]

In [ ]:
colspecs = [
    (0, 2), (2, 10), (10, 12), (12, 24), (24, 27), (27, 39), (39, 49),
    (49, 52), (52, 56), (56, 69), (69, 82), (82, 95), (95, 108), (108, 121),
    (121, 134), (134, 147), (147, 152), (152, 170), (170, 188), (188, 201),
    (201, 202), (202, 210), (210, 217), (217, 230), (230, 242), (242, 245),
]

col_origem = [
    "tipreg", "data", "codbdi", "codneg", "tpmerc", "nomres", "especi",
    "prazot", "modref", "preabe", "premax", "premin", "premed", "preult",
    "preofc", "preofv", "totneg", "quatot", "voltot", "preexe", "indopc",
    "datven", "fatcot", "ptoexe", "codisi", "dismes",
]

colunas = [
    "data", "codbdi", "codneg", "tpmerc", "nomres", "especi",
    "preabe", "premax", "premin", "premed", "preult",
    "totneg", "quatot", "voltot", "fatcot",
]

dados = {}
for i in range(len(nomes_arquivos)):
  arquivo = nomes_arquivos[i]
  aaa = pd.read_fwf(
            f"{caminho_dados}/{arquivo}",
            colspecs=colspecs,
            names=col_origem,
            dtype=str,
            encoding="latin-1"
        )
  aaa = aaa[colunas]
  dados[i] = aaa
  print(f"Arquivo lido: {arquivo}; Tamanho: {aaa.shape}")
print("Funcionou!!")

Arquivo lido: COTAHIST_A2025.TXT; Tamanho: (3174700, 15)
Arquivo lido: COTAHIST_A2024.TXT; Tamanho: (2635563, 15)
Arquivo lido: COTAHIST_A2023.TXT; Tamanho: (2257426, 15)
Arquivo lido: COTAHIST_A2022.TXT; Tamanho: (2117442, 15)
Arquivo lido: COTAHIST_A2021.TXT; Tamanho: (1831864, 15)
Arquivo lido: COTAHIST_A2020.TXT; Tamanho: (1251648, 15)
Arquivo lido: COTAHIST_A2019.TXT; Tamanho: (779231, 15)
Arquivo lido: COTAHIST_A2018.TXT; Tamanho: (580157, 15)
Arquivo lido: COTAHIST_A2017.TXT; Tamanho: (489117, 15)
Arquivo lido: COTAHIST_A2016.TXT; Tamanho: (466736, 15)
Funcionou!!

In [ ]:
df_analisado = 0

dados[0].head()

,data,codbdi,codneg,tpmerc,nomres,especi,preabe,premax,premin,premed,preult,totneg,quatot,voltot,fatcot
0,COTAHIST,.2,025BOVESPA 2,025,1230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250120,12,ITIP11,010,FII INTER IP,CI,0000000006900,0000000006924,0000000006808,0000000006830,0000000006839,00059,000000000000001125,000000000007684751,0000001
2,20250120,12,ITIT11,010,FII INTER IT,CI,0000000006705,0000000006706,0000000006678,0000000006699,0000000006701,00043,000000000000001686,000000000011295441,0000001
3,20250120,34,ITLC34,010,INTEL,DRN,0000000002152,0000000002293,0000000002152,0000000002247,0000000002261,02020,000000000000145538,000000000327059441,0000001
4,20250120,12,ITRI11,010,FII ITRI,CI,0000000006665,0000000006738,0000000006626,0000000006669,0000000006671,02518,000000000000017546,000000000117022090,0000001

In [ ]:
base_completa = pd.DataFrame(columns = ["origem"]+colunas)
base_completa

Empty DataFrame
Columns: [origem, data, codbdi, codneg, tpmerc, nomres, especi, preabe, premax, premin, premed, preult, totneg, quatot, voltot, fatcot]
Index: []

In [ ]:
lista_dfs = []

for i in dados:
    df = dados[i]
    df["origem"] = df.iloc[0, 3]
    df = df[df['data'] != 'COTAHIST']
    lista_dfs.append(df)
    # dados[i] = "Concluído"

base_completa = pd.concat(lista_dfs, ignore_index=True)
del lista_dfs, df

In [ ]:
print(base_completa.shape, base_completa.dtypes)
base_completa.head()

(15583864, 16) data      object
codbdi    object
codneg    object
tpmerc    object
nomres    object
especi    object
preabe    object
premax    object
premin    object
premed    object
preult    object
totneg    object
quatot    object
voltot    object
fatcot    object
origem    object
dtype: object

,data,codbdi,codneg,tpmerc,nomres,especi,preabe,premax,premin,premed,preult,totneg,quatot,voltot,fatcot,origem
0,20250120,12,ITIP11,010,FII INTER IP,CI,0000000006900,0000000006924,0000000006808,0000000006830,0000000006839,00059,000000000000001125,000000000007684751,0000001,025
1,20250120,12,ITIT11,010,FII INTER IT,CI,0000000006705,0000000006706,0000000006678,0000000006699,0000000006701,00043,000000000000001686,000000000011295441,0000001,025
2,20250120,34,ITLC34,010,INTEL,DRN,0000000002152,0000000002293,0000000002152,0000000002247,0000000002261,02020,000000000000145538,000000000327059441,0000001,025
3,20250120,12,ITRI11,010,FII ITRI,CI,0000000006665,0000000006738,0000000006626,0000000006669,0000000006671,02518,000000000000017546,000000000117022090,0000001,025
4,20250120,02,ITSA3,010,ITAUSA,ON N1,0000000000920,0000000000934,0000000000914,0000000000926,0000000000931,00372,000000000000098000,000000000090797800,0000001,025

In [ ]:
del dados

##Convertendo Colunas

In [ ]:
print(colunas)
base_completa.head()

['data', 'codbdi', 'codneg', 'tpmerc', 'nomres', 'especi', 'preabe', 'premax', 'premin', 'premed', 'preult', 'totneg', 'quatot', 'voltot', 'fatcot']

,data,codbdi,codneg,tpmerc,nomres,especi,preabe,premax,premin,premed,preult,totneg,quatot,voltot,fatcot,origem
0,20250120,12,ITIP11,010,FII INTER IP,CI,0000000006900,0000000006924,0000000006808,0000000006830,0000000006839,00059,000000000000001125,000000000007684751,0000001,025
1,20250120,12,ITIT11,010,FII INTER IT,CI,0000000006705,0000000006706,0000000006678,0000000006699,0000000006701,00043,000000000000001686,000000000011295441,0000001,025
2,20250120,34,ITLC34,010,INTEL,DRN,0000000002152,0000000002293,0000000002152,0000000002247,0000000002261,02020,000000000000145538,000000000327059441,0000001,025
3,20250120,12,ITRI11,010,FII ITRI,CI,0000000006665,0000000006738,0000000006626,0000000006669,0000000006671,02518,000000000000017546,000000000117022090,0000001,025
4,20250120,02,ITSA3,010,ITAUSA,ON N1,0000000000920,0000000000934,0000000000914,0000000000926,0000000000931,00372,000000000000098000,000000000090797800,0000001,025

In [ ]:
list(base_completa['tpmerc'].unique())

['010', '020', '021', '017', '030', '070', '013', '012', '080']

In [ ]:
## Data
base_completa['data'] = pd.to_datetime(base_completa['data'], format='%Y%m%d')

## Índices e Valores
numericos = ['preabe', 'premax', 'premin', 'premed', 'preult', 'totneg', 'quatot', 'voltot', 'fatcot']
base_completa[numericos] = base_completa[numericos].apply(pd.to_numeric, errors='coerce')
base_completa[['preabe', 'premax', 'premin', 'premed', 'preult']] = base_completa[['preabe', 'premax', 'premin', 'premed', 'preult']] / 100

In [ ]:
base_completa.head()

,data,codbdi,codneg,tpmerc,nomres,especi,preabe,premax,premin,premed,preult,totneg,quatot,voltot,fatcot,origem
0,2025-01-20,12,ITIP11,010,FII INTER IP,CI,69.00,69.24,68.08,68.30,68.39,59,1125,7684751,1,025
1,2025-01-20,12,ITIT11,010,FII INTER IT,CI,67.05,67.06,66.78,66.99,67.01,43,1686,11295441,1,025
2,2025-01-20,34,ITLC34,010,INTEL,DRN,21.52,22.93,21.52,22.47,22.61,2020,145538,327059441,1,025
3,2025-01-20,12,ITRI11,010,FII ITRI,CI,66.65,67.38,66.26,66.69,66.71,2518,17546,117022090,1,025
4,2025-01-20,02,ITSA3,010,ITAUSA,ON N1,9.20,9.34,9.14,9.26,9.31,372,98000,90797800,1,025

## Exportando Bases

In [ ]:
base_completa[~base_completa['tpmerc'].isin(["010"])]#.unique()

,data,codbdi,codneg,tpmerc,nomres,especi,preabe,premax,premin,premed,preult,totneg,quatot,voltot,fatcot,origem
405,2025-01-20,96,AGRO3F,020,BRASILAGRO,ON NM,22.37,22.61,22.37,22.50,22.48,822,8523,19177033,1,025
406,2025-01-20,96,AGXY3F,020,AGROGALAXY,ON NM,0.73,0.84,0.64,0.74,0.73,612,11223,839866,1,025
407,2025-01-20,96,ALLD3F,020,ALLIED,ON NM,7.05,7.05,6.75,6.84,6.78,407,3447,2360856,1,025
408,2025-01-20,96,ALOS3F,020,ALLOS,ON NM,18.06,18.24,17.73,17.99,18.12,515,7482,13462800,1,025
409,2025-01-20,96,BBDC3F,020,BRADESCO,ON N1,10.65,10.76,10.58,10.68,10.75,2431,29199,31207174,1,025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15583846,2016-12-29,96,VVAR11F,020,VIAVAREJO,UNT N2,10.89,10.89,10.42,10.67,10.57,14,310,331070,1,016
15583848,2016-12-29,96,VVAR3F,020,VIAVAREJO,ON N2,3.61,3.61,3.60,3.60,3.60,2,100,36095,1,016
15583852,2016-12-29,96,WEGE3F,020,WEG,ON NM,15.13,15.72,14.87,15.25,15.42,56,1524,2325126,1,016
15583853,2016-12-29,62,WEGE3T,030,WEG,ON NM,15.50,15.54,15.50,15.51,15.54,4,25500,39555553,1,016
15583854,2016-12-29,62,WEGE3T,030,WEG,ON NM,15.70,15.71,15.70,15.70,15.71,2,900,1413855,1,016

In [ ]:
base_completa[base_completa['tpmerc'] == "010"].to_csv(f"{caminho_output}/dados_acoes.csv")

In [ ]:
base_completa[~(base_completa['tpmerc'] == "010")].to_csv(f"{caminho_output}/dados_a_prazo.csv")